buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'java'
    id 'net.neoforged.moddev.legacyforge' version '2.0.91'
}

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://modmaven.dev/' }
}

dependencies {
    modImplementation("appeng:appliedenergistics2-forge:${ae2_version}") { transitive = false }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

tasks.named('processResources', ProcessResources).configure {
    def props = [
            minecraft_version: minecraft_version,
            forge_version: forge_version,
            ae2_version: ae2_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version
    ]
    inputs.properties props
    filesMatching('META-INF/mods.toml') {
        expand props
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes 'MixinConfigs': "${mod_id}.mixins.json"
    }
}
